apiVersion: v1
kind: Service
metadata:
  name: solarma-site
  labels:
    app.kubernetes.io/name: solarma-site
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: solarma-site
  ports:
    - {name: http, port: 80, targetPort: http, protocol: TCP}
